// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Kader_System.DataAccess.Models;

public partial class Client
{
    public int ClientId { get; set; }

    public string ClientNameAr { get; set; }

    public string ClientNameEn { get; set; }

    public string Mobile { get; set; }

    public string Email { get; set; }

    public int? TaxRegNum { get; set; }

    public string TaxFacilityName { get; set; }

    public int? ClientCode { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public int? AddUser { get; set; }

    public DateTime? AddDate { get; set; }

    public bool ClientActive { get; set; }

    public DateTime? DisableDate { get; set; }

    public int? DisableUser { get; set; }

    public bool Status { get; set; }

    public string ProjectId { get; set; }

    public string Users { get; set; }

    public int NoticePeriod { get; set; }

    public string DeviceName { get; set; }

    public string MacAddress { get; set; }

    public string IpAddress { get; set; }
}