// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Kader_System.Domain.Models;

public partial class Client
{
    public int client_id { get; set; }

    public string client_name_ar { get; set; }

    public string client_name_en { get; set; }

    public string mobile { get; set; }

    public string email { get; set; }

    public int? tax_reg_num { get; set; }

    public string tax_facility_name { get; set; }

    public int? client_code { get; set; }

    public DateOnly? start_date { get; set; }

    public DateOnly? end_date { get; set; }

    public int? add_user { get; set; }

    public DateTime? add_date { get; set; }

    public bool client_active { get; set; }

    public DateTime? disable_date { get; set; }

    public int? disable_user { get; set; }

    public bool status { get; set; }

    public string project_id { get; set; }

    public string users { get; set; }

    public int notice_period { get; set; }
}