// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Kader_System.DataAccess.Models;

public partial class KaderAuthorizationContext : DbContext
{
    public KaderAuthorizationContext(DbContextOptions<KaderAuthorizationContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Client> Clients { get; set; }

  




    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Client>(entity =>
        {
            entity.HasKey(e => e.ClientId).HasName("PK__Client__BF21A424DDD8A84D");

            entity.ToTable("clients");

            entity.HasIndex(e => new { e.ClientCode, e.DeviceName, e.MacAddress, e.IpAddress }, "UQ__Client__7877F880830D77E2").IsUnique();

            entity.Property(e => e.ClientId).HasColumnName("client_id");
            entity.Property(e => e.AddDate)
                .HasColumnType("datetime")
                .HasColumnName("add_date");
            entity.Property(e => e.AddUser).HasColumnName("add_user");
            entity.Property(e => e.ClientActive).HasColumnName("client_active");
            entity.Property(e => e.ClientCode).HasColumnName("client_code");
            entity.Property(e => e.ClientNameAr)
                .HasMaxLength(255)
                .HasColumnName("client_name_ar");
            entity.Property(e => e.ClientNameEn)
                .HasMaxLength(255)
                .HasColumnName("client_name_en");
            entity.Property(e => e.DeviceName)
                .HasMaxLength(255)
                .HasColumnName("device_name");
            entity.Property(e => e.DisableDate)
                .HasColumnType("datetime")
                .HasColumnName("disable_date");
            entity.Property(e => e.DisableUser).HasColumnName("disable_user");
            entity.Property(e => e.Email)
                .HasMaxLength(255)
                .HasColumnName("email");
            entity.Property(e => e.EndDate)
                .HasColumnType("datetime")
                .HasColumnName("end_date");
            entity.Property(e => e.IpAddress)
                .HasMaxLength(255)
                .HasColumnName("ip_address");
            entity.Property(e => e.MacAddress)
                .HasMaxLength(255)
                .HasColumnName("mac_address");
            entity.Property(e => e.Mobile)
                .HasMaxLength(50)
                .HasColumnName("mobile");
            entity.Property(e => e.NoticePeriod).HasColumnName("notice_period");
            entity.Property(e => e.ProjectId)
                .HasMaxLength(255)
                .HasColumnName("project_id");
            entity.Property(e => e.StartDate)
                .HasColumnType("datetime")
                .HasColumnName("start_date");
            entity.Property(e => e.Status).HasColumnName("status");
            entity.Property(e => e.TaxFacilityName)
                .HasMaxLength(255)
                .HasColumnName("tax_facility_name");
            entity.Property(e => e.TaxRegNum).HasColumnName("tax_reg_num");
            entity.Property(e => e.Users).HasColumnName("users");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}