// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Kader_System.DataAccess.Context;

public partial class KaderAuthorizationContext : DbContext
{
    public KaderAuthorizationContext(DbContextOptions<KaderAuthorizationContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Client> Clients { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Client>(entity =>
        {
            entity.HasKey(e => e.client_id).HasName("PK__clients__BF21A4249C5D37EB");

            entity.ToTable("clients");

            entity.Property(e => e.client_id).HasColumnName("client_id");
            entity.Property(e => e.add_date)
                .HasColumnType("datetime")
                .HasColumnName("add_date");
            entity.Property(e => e.add_user).HasColumnName("add_user");
            entity.Property(e => e.client_active)
                .HasDefaultValue(true)
                .HasColumnName("client_active");
            entity.Property(e => e.client_code).HasColumnName("client_code");
            entity.Property(e => e.client_name_ar)
                .HasMaxLength(100)
                .HasColumnName("client_name_ar");
            entity.Property(e => e.client_name_en)
                .HasMaxLength(100)
                .HasColumnName("client_name_en");
            entity.Property(e => e.disable_date)
                .HasColumnType("datetime")
                .HasColumnName("disable_date");
            entity.Property(e => e.disable_user).HasColumnName("disable_user");
            entity.Property(e => e.email)
                .HasMaxLength(100)
                .HasColumnName("email");
            entity.Property(e => e.end_date).HasColumnName("end_date");
            entity.Property(e => e.mobile)
                .HasMaxLength(15)
                .HasColumnName("mobile");
            entity.Property(e => e.notice_period)
                .HasDefaultValue(7)
                .HasColumnName("notice_period");
            entity.Property(e => e.project_id).HasColumnName("project_id");
            entity.Property(e => e.start_date).HasColumnName("start_date");
            entity.Property(e => e.status)
                .HasDefaultValue(true)
                .HasColumnName("status");
            entity.Property(e => e.tax_facility_name)
                .HasMaxLength(100)
                .HasColumnName("tax_facility_name");
            entity.Property(e => e.tax_facility_name).HasColumnName("tax_reg_num");
            entity.Property(e => e.users).HasColumnName("users");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}